eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8002
spring:
  application:
    name: eureka-feign
feign:
  hystrix:
    enabled: true
# management.endpoints.web.exposure.include这个是用来暴露 endpoints 的
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream