spring:
  application:
    name: turbine
server:
  port: 8004
management:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
turbine:
  app-config: eureka-feign
  cluster-name-expression: new String("default")
  combine-host-port: true